version: "3"
services:
  mariadb:
    image: mariadb:10.4-bionic
    environment:
      MYSQL_ROOT_PASSWORD: password

  bimroad:
    image: danacr/bimroad:latest
    container_name: bimroad
    ports:
      - 8080:8080

  ngrok:
    image: wernight/ngrok
    command: ngrok http bimroad:8080
    ports: 
      - 4040:4040

