version: "3"
services:
  bimroad:
    image: danacr/bimroad
    container_name: bimroad
    ports:
      - 8080:80
    volumes:
      - persistence:/usr/src/app/

  ngrok:
    image: wernight/ngrok
    command: ngrok http bimroad:80
    ports:
      - 8082:4040

volumes:
  persistence:
